name: 📄 Hugo GitHub Pages
author: tomy0000000
description: Build Hugo site for GitHub Pages

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
        extended: true

    - name: ⚙️ Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: 🏗️ Build with Hugo
      shell: bash
      run: |
        hugo --gc --minify --baseURL ${{ steps.pages.outputs.base_url }}

    - name: ⬆️ Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

branding:
  icon: layout
  color: red
