name: 📄 Hugo GitHub Pages
author: tomy0000000
description: Build Hugo site for GitHub Pages

inputs:
  hugo_version:
    description: "Version for Hugo"
    required: false
    default: "latest"
  upload:
    description: "Upload Artifact"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ inputs.hugo_version }}
        extended: true

    - name: ⚙️ Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: 🏗️ Build with Hugo
      shell: bash
      run: |
        hugo --gc --minify --baseURL ${{ steps.pages.outputs.base_url }}

    - name: ⬆️ Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: ${{ inputs.upload == 'true' }}
      with:
        path: ./public

branding:
  icon: layout
  color: red
