name: "🐍 Setup Poetry"
author: tomy0000000
description: Setup Python and install dependencies with Poetry

inputs:
  python_version:
    description: "Version for Python"
    required: true

runs:
  using: composite
  steps:
    - name: "🐍 Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: "📦 Install Dependencies"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

branding:
  icon: box
  color: green
